config/routes.rb
Railsgirls::Application.routes.draw do

  root :to => redirect('/attendees')
  resources :attendees

end

app/models/attendee.rb
class Attendee < ActiveRecord::Base
  attr_accessible :address, :bio, :name, :picture, :twitter_handle, :comment
  mount_uploader :picture, PictureUploader

  validates_presence_of :name

  geocoded_by :address
  after_validation :geocode

  acts_as_gmappable :process_geocoding => false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController
  # GET /attendees
  # GET /attendees.json
  def index
    @attendees = Attendee.all
    @pins = @attendees.to_gmaps4rails

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @attendees }
    end
  end

  # GET /attendees/1
  # GET /attendees/1.json
  def show
    @attendee = Attendee.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @attendee }
    end
  end

  # GET /attendees/new
  # GET /attendees/new.json
  def new
    @attendee = Attendee.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @attendee }
    end
  end

  # GET /attendees/1/edit
  def edit
    @attendee = Attendee.find(params[:id])
  end

  # POST /attendees
  # POST /attendees.json
  def create
    @attendee = Attendee.new(params[:attendee])

    respond_to do |format|
      if @attendee.save
        format.html { redirect_to @attendee, notice: 'Attendee was successfully created.' }
        format.json { render json: @attendee, status: :created, location: @attendee }
      else
        format.html { render action: "new" }
        format.json { render json: @attendee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /attendees/1
  # PUT /attendees/1.json
  def update
    @attendee = Attendee.find(params[:id])

    respond_to do |format|
      if @attendee.update_attributes(params[:attendee])
        format.html { redirect_to @attendee, notice: 'Attendee was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @attendee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attendees/1
  # DELETE /attendees/1.json
  def destroy
    @attendee = Attendee.find(params[:id])
    @attendee.destroy

    respond_to do |format|
      format.html { redirect_to attendees_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendees_helper.rb
module AttendeesHelper
end

app/views/attendees/_form.html.erb
<%= form_for(@attendee, :html => { :multipart => true }) do |f| %>
  <% if @attendee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attendee.errors.count, "error") %> prohibited this attendee from being saved:</h2>

      <ul>
      <% @attendee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :twitter_handle %><br />
    <%= f.text_field :twitter_handle %>
  </div>
  <div class="field">
    <%= f.label :bio %><br />
    <%= f.text_area :bio %>
  </div>
  <div class="field">
    <%= f.label :address, 'Hometown' %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :picture %><br />
    <%= f.file_field :picture %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/attendees/edit.html.erb
<h1>Editing attendee</h1>

<%= render 'form' %>

<%= link_to 'Show', @attendee %> |
<%= link_to 'Back', attendees_path %>

app/views/attendees/index.html.erb
<h1>Rails Girls Berlin at eurucamp</h1>

<%#= gmaps4rails(@pins) %>
<%= gmaps("markers" => { "data" => @pins }, "map_options" => { "center_longitude" => 13.24, "center_latitude" => 52.31, "zoom" => 7 }) %>
<%= yield :scripts %>

<table>
  <tr>
    <th class='first'></th>
    <th>Name</th>
    <th>Twitter handle</th>
    <th>Hometown</th>
  </tr>

<% @attendees.each do |attendee| %>
  <tr>
    <td class="first"><%= image_tag(attendee.picture.thumb.url) unless attendee.picture.thumb.blank? %></td>
    <td><%= link_to(attendee.name, attendee) %></td>
    <td><%= link_to(attendee.twitter_handle, "http://twitter.com/#{attendee.twitter_handle}", :target => '_blank') if attendee.twitter_handle %></td>
    <td><%= attendee.address %></td>
  </tr>
<% end %>
</table>

<br />

<br />
<%= link_to 'New Attendee', new_attendee_path %>

app/views/attendees/new.html.erb
<h1>New attendee</h1>

<%= render 'form' %>

<%= link_to 'Back', attendees_path %>

app/views/attendees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @attendee.name %>
</p>

<p>
  <b>Twitter handle:</b>
  <%= @attendee.twitter_handle %>
</p>

<p>
  <b>Bio:</b>
  <%= @attendee.bio %>
</p>

<p>
  <b>Address:</b>
  <%= @attendee.address %>
</p>

<p>
  <b>Picture:</b>
  <%= image_tag(@attendee.picture.url, :width => 600) if @attendee.picture.present? %>
</p>

<p>
  <b>Comment:</b>
  <%= @attendee.comment %>
</p>


<%= link_to 'Edit',    edit_attendee_path(@attendee) %> |
<%= link_to 'Destroy', attendee_path(@attendee), :method => :delete, :confirm => "Are you sure?" %> |
<%= link_to 'Index',   attendees_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Railsgirls</title>
  <link rel="stylesheet" href="http://railsgirls.com/assets/bootstrap.css">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="brand" href="/">The workshop app</a>
          <ul class="nav">
            <li class="active"><a href="/attendees">Attendees</a></li>
        </ul>
      </div>
    </div>
  </div>

  <div class="container">
    <%= yield %>
  </div>
  <footer>
    <div class="container">
      Rails Girls Berlin 2012
    </div>
  </footer>
</body>
</html>